#!/bin/bash

#PBS -l walltime=72:00:00
#PBS -l select=1:ncpus=128:mem=920gb

# Job sizing guidance:imperial college's Intro to HPC OR
# https://www.imperial.ac.uk/computational-methods/hpc/
source ~/anaconda3/etc/profile.d/conda.sh

cd $PBS_O_WORKDIR
#mkdir /trialFolder # Failed
conda run -n R_envConda Rscript 2_mlesky_1e5.R "mcmc_bacdating.rds" 2 TRUE 128 > myresult.txt
#mv *.pdf myresult.txt $PBS_O_WORKDIR

printenv > myenv.txt
#mv myenv.txt $PBS_O_WORKDIR
